spring:
  application:
    name: USER-SERVICE

  profiles:
    active: localhost

server:
  port: 8766

---



eureka:
  instance:
    hostname: user-service
    instance-id: ${spring.application.name}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

---

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_service
    username: itg
    password: itg
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  issuer_uri: http://localhost:8080/realms/java-microservice-realm/protocol/openid-connect/token
  client_id: spring-cloud-client
  client_secret: AJufwN1eof8P5Gga5Y9atCFqdMuZEuKd
  grant_type: client_credentials
  scope: openid offline_access
